name: AsciiDoc to Reveal.js

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        container:
            image: docker.io/asciidoctor/docker-asciidoctor:latest
            volumes:
                - .:/documents
        
        env:
            REVEALJS_DIR: https://cdn.jsdelivr.net/npm/reveal.js@5.1.0

        steps:
            - uses: actions/checkout@v4

            - name: Generate Reveal.js presentation
              run: asciidoctor-revealjs -a revealjsdir=${REVEALJS_DIR} -r asciidoctor-kroki index.adoc

            - name: Commit and push changes
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    BRANCH: gh-pages
                    FOLDER: output
            - uses: actions/download-artifact@master
              with:
                name: page
                path: .
            - uses: actions/configure-pages@v4
            - uses: actions/upload-pages-artifact@v3
              with:
                path: .
            - id: deployment
              uses: actions/deploy-pages@main